### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/flippy#8]
I suggest you add under Linux a section for Debian, or modify the existing section:

```
sudo apt-get install python-pip
sudo pip install Pillow fpdf moviepy
```

to make installation easier for the Linux users.

**Comment by Wikinaut** [comment]
On my system, I had to use `sudo` as in

```
sudo pip install Pillow fpdf moviepy
```

to avoid 

```
error: could not create '/usr/local/lib/python2.7/dist-packages/fpdf': Permission denied
```

when installing as a user, but this is perhaps a matter of /usr/local/lib permissions. I don't know.

**Comment by 607011** [comment]
The project now uses Python 3 and [Pipenv](https://github.com/pypa/pipenv). So it's no longer necessary the install the required modules manually.

**Comment by Wikinaut** [comment]
I installed ```pipenv``` and had this ```https://github.com/pypa/pipenv/issues/3827``` locking issue. After clearing the python cache I now got this error with your code:

```
./flippy.py
usage: flippy.py [-h] [--out OUT] [--height HEIGHT] [--paper {a5,a4,a3,letter,legal}] [--offset OFFSET] [--phena] [--dpi DPI] [--fps FPS] [-v [V]] video
flippy.py: error: the following arguments are required: video
```

and with the video file as input parameter I got

```
./flippy.py 1.mp4
Traceback (most recent call last):
  File "./flippy.py", line 277, in <module>
    main()
  File "./flippy.py", line 265, in main
    flippy = FlipbookCreator(
  File "./flippy.py", line 107, in __init__
    self.clip = VideoFileClip(self.input_file_name)
NameError: name 'VideoFileClip' is not defined
```

**Comment by ArisNeander** [comment]
> NameError: name 'VideoFileClip' is not defined

Line 14 must be changed from
`# from moviepy.editor import *`
to
`from moviepy.video.io.VideoFileClip import VideoFileClip`
